# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Thesaurus-DBI
version:      0.01
version_from: lib/Thesaurus/DBI.pm
installdirs:  site
requires:
    DBI:                           1
    Thesaurus:                     0.21

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
